### ISSUE TITLE
Prepare a wrapper function for plotting predictions / maps

### ISSUE THREAD

**Issue by thengl** [OpenGeoHub/spatial-sampling-ml#4]
The current tutorial has longer code to plot maps, add title and customize plots. It would be nicer to use a wrapper function with plotting specifications e.g.:

```r
plot.map <- function(x, y, mtext, ...){
}
```

where `x` is the grid, `y` are the points. For plotting comparison e.g. 2 maps next to each other we would need e.g.:

```r
compare.map <- function(x.left, y.left, x.right, y.right, mtext, ...){
}
```

@abdelkrim-bsr  can you please add this function and systematically adjust in the text?

**Comment by abdelkrim-bsr** [comment]
Good idea! I will look how many wrapper functions to implement.
